# Generated by Django 5.0.2 on 2024-03-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_fotografia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
